version: '3.7'

services:

  osrm:
    image: krizius/osrm-server-cz:latest
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    networks:
      - persistence
    deploy:
      restart_policy:
        condition: on-failure

networks:
  persistence:
    external: true
