version: '3.7'

services:

  redis:
    image: redis:6
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    ports:
      - 6379:6379
    volumes:
      - ./volumes/redis/data:/data
    networks:
      - persistence
    deploy:
      restart_policy:
        condition: on-failure

networks:
  persistence:
    external: true
