version: '3.7'

services:
  tor-node:
    image: osminogin/tor-simple
    ports:
      - "9051:9051"
      - "9050:9050"
    networks:
      - persistence
      - inbound

networks:
  persistence:
    external: true
  inbound:
    external: true